# Generated by Django 3.1.2 on 2020-10-06 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('category', models.CharField(max_length=10, null=True)),
                ('thumbnail', models.CharField(max_length=300)),
                ('heart_count', models.IntegerField(default=0, null=True)),
                ('like', models.IntegerField(default=0, null=True)),
                ('retail_price', models.IntegerField(default=0, null=True)),
                ('discount_percent', models.IntegerField(default=0, null=True)),
                ('monthly_pay', models.IntegerField(default=0, null=True)),
                ('monthly_payment', models.IntegerField(default=0, null=True)),
                ('brand', models.CharField(max_length=50, null=True)),
                ('sub_category', models.CharField(max_length=50, null=True)),
                ('level', models.CharField(max_length=50, null=True)),
                ('cover_image', models.CharField(max_length=100, null=True)),
                ('introduce_image', models.CharField(max_length=300, null=True)),
                ('introduce_text', models.CharField(max_length=100, null=True)),
                ('end_datetime', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='DetailImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detailImage', models.CharField(max_length=300)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.products')),
            ],
            options={
                'db_table': 'detailImage',
            },
        ),
    ]
