# Generated by Django 3.1.2 on 2020-10-06 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20201006_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'brand',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'level',
            },
        ),
        migrations.RenameField(
            model_name='products',
            old_name='brand',
            new_name='detail_category',
        ),
        migrations.RemoveField(
            model_name='products',
            name='level',
        ),
        migrations.RemoveField(
            model_name='products',
            name='sub_category',
        ),
        migrations.AlterModelTable(
            name='introduction',
            table='introduction',
        ),
        migrations.AddField(
            model_name='products',
            name='brand_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.brand'),
        ),
        migrations.AddField(
            model_name='products',
            name='level_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.level'),
        ),
    ]
